theme:
  name: material
  features:
      - navigation.sections  # Sections are included in the navigation on the left.
      - toc.integrate  # Table of contents is integrated on the left; does not appear separately on the right.
      - header.autohide  # header disappears as you scroll

site_name: PyDTS
site_description: The documentation for the PyDTS software library.
site_author: Tomer Meir, Rom Gutman

repo_url: https://github.com/tomer1812/pydts/
repo_name: tomer1812/pydts
edit_uri: ""  # No edit button, as some of our pages are in /docs and some in /examples_utils via symlink, so it's impossible for them all to be accurate

strict: false  # Don't allow warnings during the build process

markdown_extensions:
    - pymdownx.highlight:
        anchor_linenums: true
    - pymdownx.inlinehilite
    - pymdownx.arithmatex:  # Render LaTeX via MathJax
        generic: true
    - pymdownx.superfences  # Seems to enable syntax highlighting when used with the Material theme.
    - pymdownx.details  # Allowing hidden expandable regions denoted by ???
    - pymdownx.snippets:  # Include one Markdown file into another
        base_path: docs
    - admonition
    - toc:
        permalink: "¤"  # Adds a clickable permalink to each section heading
        toc_depth: 4  # Prevents h5, h6 from showing up in the TOC.

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js


nav:
    - Home: 'index.md'
    - Introduction: intro.md
    - Methods: methods.md
    - Examples:
      - Usage Example:
        - Introduction: UsageExample-Intro.ipynb
        - Data Preparation: UsageExample-DataPreparation.ipynb
        - Fitting Two Stages Fitter: UsageExample-FittingTwoStagesFitter.ipynb
        - Fitting Data Expansion Fitter: UsageExample-FittingDataExpansionFitter.ipynb
      - Data Regrouping Example: UsageExample-RegroupingData.ipynb
      - Models Comparison: ModelsComparison.ipynb
      - Hospitalization LOS Simulation: SimulatedDataset.ipynb
    - API:
      - 'api/two_stages_fitter.md'
      - 'api/data_expansion_fitter.md'

plugins:
  - mknotebooks
  - search
  - mkdocstrings

extra:
  copyright: Copyright &copy; 2022 Tomer Meir, Rom Gutman, Malka Gorfine
