theme:
  name: material

site_name: PyDTS
site_description: The documentation for the PyDTS software library.
site_author: Tomer Meir, Rom Gutman

repo_url: https://github.com/tomer1812/pydts/
repo_name: tomer1812/pydts
edit_uri: ""  # No edit button, as some of our pages are in /docs and some in /examples via symlink, so it's impossible for them all to be accurate

strict: false  # Don't allow warnings during the build process

markdown_extensions:
    - pymdownx.highlight:
        anchor_linenums: true
    - pymdownx.inlinehilite
    - pymdownx.arithmatex:  # Render LaTeX via MathJax
        generic: true
    - pymdownx.superfences  # Seems to enable syntax highlighting when used with the Material theme.
    - pymdownx.details  # Allowing hidden expandable regions denoted by ???
    - pymdownx.snippets:  # Include one Markdown file into another
        base_path: docs
    - admonition
    - toc:
        permalink: "¤"  # Adds a clickable permalink to each section heading
        toc_depth: 4  # Prevents h5, h6 from showing up in the TOC.

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js


nav:
    - 'index.md'
    - Examples:
      - QuickStart.ipynb
      - SimulatedDataset.ipynb

plugins:
  - mknotebooks
  - search
  - mkdocstrings

extra:
  copyright: Copyright &copy; 2022 Tomer Meir, Rom Gutman, Malka Gorfine
