name: Tests
on: [push, pull_request]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.8]
        os: [ubuntu-latest, macOS-latest]
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.8
        architecture: x64
    - run: pip install poetry==1.1.13
    - run: poetry install
    - run: poetry run pytest tests/
